from __future__ import annotations

import json
from dataclasses import asdict

from openai import OpenAI

from .youtube import Video, discover_videos, transcript


class SummaryError(RuntimeError):
    pass


SYSTEM_PROMPT = """You are a careful video research assistant.
Summarize only from the transcript and metadata provided by the caller. Do not invent claims, numbers, prices, or investment advice.

Return valid JSON only, without Markdown fences. The JSON shape must be:
{"overview":"cross-video summary, or the core conclusion for a single video","videos":[{"video_id":"...","title":"...","summary":"one paragraph summary","points":["point 1","point 2","point 3"],"takeaway":"one sentence conclusion"}]}

Write the JSON values in natural Traditional Chinese for Taiwan readers. Keep important numbers, dates, caveats, uncertainty, and speaker intent. Each video should include 3 to 6 concrete, non-duplicative points."""


def summarize_url(url: str, api_key: str, model: str = "gpt-4.1-mini") -> dict:
    try:
        videos = discover_videos(url, limit=4)
        materials = [_material(video) for video in videos]
    except Exception as exc:
        raise SummaryError(str(exc)) from exc

    client = OpenAI(api_key=api_key)
    try:
        response = client.responses.create(
            model=model,
            instructions=SYSTEM_PROMPT,
            input=json.dumps(materials, ensure_ascii=False),
        )
        result = json.loads(response.output_text)
    except json.JSONDecodeError as exc:
        raise SummaryError("The AI response was not valid JSON. Please try again.") from exc
    except Exception as exc:
        raise SummaryError(f"Summary service call failed: {exc}") from exc

    by_id = {video.video_id: video for video in videos}
    for item in result.get("videos", []):
        video = by_id.get(item.get("video_id"))
        if video:
            item["url"] = video.url
            item["duration"] = video.duration
            item["upload_date"] = video.upload_date
            item["view_count"] = video.view_count
    result["disclaimer"] = (
        "This summary was generated by AI from public transcript text and may contain errors. "
        "Verify important details against the original video."
    )
    return result


def _material(video: Video) -> dict:
    try:
        text = transcript(video.video_id)
    except Exception as exc:
        raise SummaryError(f"Could not fetch a readable transcript for {video.title}: {exc}") from exc
    data = asdict(video)
    data["transcript"] = text[:90000]
    return data
